### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by wang-zm18** [steventhornton/Matlab-Cheatsheet#1]
When I use XeLatex to compile this tex file, it just occurs the following problem, I sincerely hope that you can help me to deal with this problem! Thank you!
![image](https://user-images.githubusercontent.com/47704679/85913902-78727580-b86b-11ea-9b06-58caadca7b52.png)

**Comment by steventhornton** [comment]
You will need to add the `-shell-escape` flag when compiling with xelatex. I'm not sure what IDE you are using but in the settings there should be somewhere you can add this flag.

If compiling from bash you would run `xelatex -shell-escape MatlabCheatsheet.tex`.
